@echo off
title "Monkey OS Build Script"
echo Building Monkey OS...
docker build -t monkey-os-builder .
echo Extracting built kernel...
docker run --name temp-os monkey-os-builder
echo Copying kernel from container to host...
docker cp temp-os:/os-build/kernel ./kernel
echo Cleaning up...
docker rm temp-os
echo Build complete. Kernel is available at ./kernel
pause